### PR TITLE
Fix rerender

### LINKED ISSUE #46: Line-graph re-renders even when data array is the same

### PR DESCRIPTION
**Pull request by amortiz**
Fixes #46

### CODE REVIEW

File: components/LineGraph/LineGraph.js [hunk 1]
```diff
@@ -88,7 +88,7 @@ class LineGraph extends Component {
     this.initialRender();
   }
 
-  componentWillReceiveProps(nextProps) {
```
Comment (amortiz) [inline components/LineGraph/LineGraph.js]: WillREceiveProps gets called before ShouldComponentUpdate, which defeats the purpose of this PR, so changed it to componentWillUpdate, which comes after

**Comment by tw15egan** [comment]
Awesome, looks good to me 👍 ✅
